/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ModsStalkerShadowOfChernobylImport } from './routes/mods/stalker/shadow-of-chernobyl'
import { Route as ModsStalkerClearSkyImport } from './routes/mods/stalker/clear-sky'
import { Route as ModsStalkerCallOfPripyatImport } from './routes/mods/stalker/call-of-pripyat'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ModsStalkerShadowOfChernobylRoute =
  ModsStalkerShadowOfChernobylImport.update({
    id: '/mods/stalker/shadow-of-chernobyl',
    path: '/mods/stalker/shadow-of-chernobyl',
    getParentRoute: () => rootRoute,
  } as any)

const ModsStalkerClearSkyRoute = ModsStalkerClearSkyImport.update({
  id: '/mods/stalker/clear-sky',
  path: '/mods/stalker/clear-sky',
  getParentRoute: () => rootRoute,
} as any)

const ModsStalkerCallOfPripyatRoute = ModsStalkerCallOfPripyatImport.update({
  id: '/mods/stalker/call-of-pripyat',
  path: '/mods/stalker/call-of-pripyat',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/mods/stalker/call-of-pripyat': {
      id: '/mods/stalker/call-of-pripyat'
      path: '/mods/stalker/call-of-pripyat'
      fullPath: '/mods/stalker/call-of-pripyat'
      preLoaderRoute: typeof ModsStalkerCallOfPripyatImport
      parentRoute: typeof rootRoute
    }
    '/mods/stalker/clear-sky': {
      id: '/mods/stalker/clear-sky'
      path: '/mods/stalker/clear-sky'
      fullPath: '/mods/stalker/clear-sky'
      preLoaderRoute: typeof ModsStalkerClearSkyImport
      parentRoute: typeof rootRoute
    }
    '/mods/stalker/shadow-of-chernobyl': {
      id: '/mods/stalker/shadow-of-chernobyl'
      path: '/mods/stalker/shadow-of-chernobyl'
      fullPath: '/mods/stalker/shadow-of-chernobyl'
      preLoaderRoute: typeof ModsStalkerShadowOfChernobylImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mods/stalker/call-of-pripyat': typeof ModsStalkerCallOfPripyatRoute
  '/mods/stalker/clear-sky': typeof ModsStalkerClearSkyRoute
  '/mods/stalker/shadow-of-chernobyl': typeof ModsStalkerShadowOfChernobylRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mods/stalker/call-of-pripyat': typeof ModsStalkerCallOfPripyatRoute
  '/mods/stalker/clear-sky': typeof ModsStalkerClearSkyRoute
  '/mods/stalker/shadow-of-chernobyl': typeof ModsStalkerShadowOfChernobylRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/mods/stalker/call-of-pripyat': typeof ModsStalkerCallOfPripyatRoute
  '/mods/stalker/clear-sky': typeof ModsStalkerClearSkyRoute
  '/mods/stalker/shadow-of-chernobyl': typeof ModsStalkerShadowOfChernobylRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mods/stalker/call-of-pripyat'
    | '/mods/stalker/clear-sky'
    | '/mods/stalker/shadow-of-chernobyl'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mods/stalker/call-of-pripyat'
    | '/mods/stalker/clear-sky'
    | '/mods/stalker/shadow-of-chernobyl'
  id:
    | '__root__'
    | '/'
    | '/mods/stalker/call-of-pripyat'
    | '/mods/stalker/clear-sky'
    | '/mods/stalker/shadow-of-chernobyl'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModsStalkerCallOfPripyatRoute: typeof ModsStalkerCallOfPripyatRoute
  ModsStalkerClearSkyRoute: typeof ModsStalkerClearSkyRoute
  ModsStalkerShadowOfChernobylRoute: typeof ModsStalkerShadowOfChernobylRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModsStalkerCallOfPripyatRoute: ModsStalkerCallOfPripyatRoute,
  ModsStalkerClearSkyRoute: ModsStalkerClearSkyRoute,
  ModsStalkerShadowOfChernobylRoute: ModsStalkerShadowOfChernobylRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/mods/stalker/call-of-pripyat",
        "/mods/stalker/clear-sky",
        "/mods/stalker/shadow-of-chernobyl"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/mods/stalker/call-of-pripyat": {
      "filePath": "mods/stalker/call-of-pripyat.tsx"
    },
    "/mods/stalker/clear-sky": {
      "filePath": "mods/stalker/clear-sky.tsx"
    },
    "/mods/stalker/shadow-of-chernobyl": {
      "filePath": "mods/stalker/shadow-of-chernobyl.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
